version: "3.9"
services:
  cad:
    command: "npm run docker-start"
    container_name: "SnailyCAD-web"
    image: node:16
    restart: always
    ports:
      - "3030:3030"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      PORT: 3030
    working_dir: /srv/api
    volumes:
      - .:/srv/api
    depends_on:
      - database

volumes:
  db_data: {}
